// client/typescript-fetch: OpenAPI -> TypeScript fetch クライアント (openapi-generator typescript-fetch 互換の出力)
import { createTs } from './ts.js';

export const meta = {
  description: 'TypeScript fetch client (openapi-generator 7.12.0 の typescript-fetch と同じ出力)',
  options: {},
};

// ファイル先頭のコメント。本家は contact が無いと " * " だけの行を出す。
function fileHeader(spec) {
  const info = spec.info ?? {};
  const desc = info.description ?? 'No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)';
  const contact = info.contact?.email ? `Contact: ${info.contact.email}` : '';
  return [
    '/* tslint:disable */',
    '/* eslint-disable */',
    '/**',
    ` * ${info.title ?? 'OpenAPI definition'}`,
    ` * ${desc}`,
    ' *',
    ` * The version of the OpenAPI document: ${info.version ?? ''}`,
    ` * ${contact}`,
    ' *',
    ' * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).',
    ' * https://openapi-generator.tech',
    ' * Do not edit the class manually.',
    ' */',
  ].join('\n');
}

export default async function generate({ spec, operations, render, write: rawWrite, log }) {
  const files = [];
  const write = (rel, content) => { files.push(rel); rawWrite(rel, content); };
  const ts = createTs(spec);
  const header = fileHeader(spec);
  // 空白だけの行はエディタに削られやすいので、テンプレートでは変数で出力する
  const common = { header, sp8: '        ' };

  const models = ts.buildModels();
  const modelNames = new Set(models.map((m) => m.classname));
  for (const m of models) {
    const view = { ...common, ...m, vars: m.vars?.map((v) => ({ ...v, typeDoc: `{${v.type.replace(/ \| null$/, '')}}` })) };
    write(`models/${m.classname}.ts`, render(m.isEnum ? 'enum' : 'model', view));
  }
  write('models/index.ts', render('index', { exports: models.map((m) => `./${m.classname}`).sort() }));

  const apis = ts.buildApis(operations, modelNames);
  for (const api of apis) write(`apis/${api.classname}.ts`, render('api', { ...common, ...api }));
  write('apis/index.ts', render('index', { exports: apis.map((a) => `./${a.classname}`).sort() }));

  let basePath = '';
  const server = spec.servers?.[0]?.url ?? '/';
  try {
    basePath = server.startsWith('/') ? server : new URL(server).href;
  } catch {
    log(`servers[0].url を解釈できません: ${server}`);
  }
  write('runtime.ts', render('runtime', { header, basePath: basePath.replace(/\/+$/, '') || '' }));
  write('index.ts', render('index', { exports: ['./runtime', './apis/index', './models/index'] }));

  // 本家が出力するメタ情報 (再生成で消えて git 差分にならないよう同じ内容を出す)
  write('.openapi-generator-ignore', render('openapi-generator-ignore', {}));
  const sorted = [...files].sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
  rawWrite('.openapi-generator/FILES', sorted.join('\n') + '\n');
  rawWrite('.openapi-generator/VERSION', '7.12.0\n');
}
