// Python サーバー系ターゲット (FastAPI / Flask / Falcon) の共通処理。
// models.py と操作ごとの ABC は 3 つで同一。ターゲットごとに違うのは router.py (と runtime.py) だけ。
//
// 方針 (生成物は人間が絶対に編集しない):
//   - 処理の実装は人間が _impl/<op>.py に <Op>ApiImpl(<Op>Api) として書く。
//     _impl は生成しない・上書きしない・削除しない。既定では出力先の 1 つ上の階層に置く。
//   - router.py が _impl をルーティングに登録する。再生成しても実装は消えない。
import { createPy } from './py.js';
import { t } from '../../lib/i18n.js';

export const GENERATED = '# Auto-generated by oag. DO NOT EDIT. 変更は OpenAPI 仕様を直して再生成してください。\n# ruff: noqa\n# flake8: noqa';

export const TEMPLATE_DIRS = ['../_python/templates'];

export const commonOptions = {
  implPackage: {
    default: '.._impl',
    description: {
      en: 'Package of the implementation classes. ".._impl" is one level above the output directory, "._impl" is directly under it, and anything not starting with "." is an absolute import',
      ja: '実装クラスのパッケージ。".._impl" は出力先の1つ上の _impl、"._impl" は出力先の直下、"." で始まらなければ絶対 import',
    },
  },
  basePath: { default: '', description: { en: 'Route prefix (default: path of servers[0].url)', ja: 'ルートの prefix (未指定なら servers[0].url のパス)' } },
};

/** 出力先の直下 ("._impl") を実装置き場にする場合だけ、その下への書き込みを拒否する */
export function guardWrite(rawWrite, implPackage) {
  const inside = /^\.(?!\.)/.test(implPackage);
  const implDir = inside ? implPackage.replace(/^\./, '').replace(/\./g, '/') : null;
  return (rel, content) => {
    if (implDir && (rel === implDir || rel.startsWith(implDir + '/'))) {
      throw new Error(t('impl_dir_guard', { path: rel, dir: implDir }));
    }
    rawWrite(rel, content);
  };
}

export function routerPrefix(spec, options, log) {
  if (options.basePath) return options.basePath;
  const server = spec.servers?.[0]?.url ?? '/';
  try {
    return new URL(server, 'http://localhost').pathname.replace(/\/$/, '');
  } catch {
    log(t('servers_url_invalid', { server }));
    return '';
  }
}

/**
 * models.py / apis/*.py (ABC) / __init__.py を書き出し、router 生成用の操作情報を返す。
 * fileType: ファイルパラメータの型 (FastAPI: 'UploadFile' / それ以外: 'Any')
 */
export function writeBase({ spec, operations, options, render, write, fileType }) {
  const py = createPy(spec, { fileType });
  const common = { generated: GENERATED };

  const { enums, models, ctx } = py.buildModels();
  write('models.py', render('models', {
    ...common,
    mods: [...ctx.mods].sort().map((m) => ({ m })),
    typingAny: ctx.typing.has('Any'),
    enums, models,
    allModels: models.map((m) => ({ classname: m.classname })),
  }));

  const ops = py.buildOperations(operations);
  const seen = new Set();
  for (const op of ops) {
    if (seen.has(op.modName)) throw new Error(t('duplicate_operation_id', { id: op.operationId }));
    seen.add(op.modName);
  }

  // 認証情報の型 AuthInfo と検証関数 verify_access_token は手書きの <implPackage>.auth に置く規約。
  // apis/ は 1 階層深いので、相対 import ならドットを 1 つ足す。
  const authFromRouter = `${options.implPackage}.auth`;
  const authFromApis = `${options.implPackage.startsWith('.') ? '.' : ''}${authFromRouter}`;
  const anySecured = ops.some((op) => op.secured);

  for (const op of ops) {
    const a = op.actx;
    write(`apis/${op.modName}_api.py`, render('api', {
      ...common,
      secured: op.secured,
      authImport: authFromApis,
      mods: [...a.mods].sort().map((m) => ({ m })),
      typingAny: a.typing.has('Any'),
      uploadFile: a.typing.has('UploadFile'),
      responseImport: op.responseClass === 'Response' && fileType === 'UploadFile',
      modelImports: [...a.models].sort().join(', '),
      hasModelImports: a.models.size > 0,
      abcName: op.abcName, methodName: op.methodName,
      summary: op.summary, description: op.description,
      operationId: op.operationId,
      args: [
        ...(op.secured ? [{ decl: 'auth: AuthInfo', name: 'auth', description: 'verify_access_token が返した認証情報' }] : []),
        ...op.params.map((p) => ({ decl: `${p.pyName}: ${p.atype}${p.required ? '' : ` = ${p.defaultValue}`}`, name: p.pyName, description: p.description })),
      ],
      returnType: op.returnA,
    }));
  }
  write('apis/__init__.py', render('apis_init', { ...common, ops }));
  write('__init__.py', render('init', common));

  return {
    ops,
    common,
    anySecured,
    authImport: { from: authFromRouter },
    abcImports: ops.map((op) => ({ mod: op.modName, abc: op.abcName })),
    implImports: ops.map((op) => ({ from: `${options.implPackage}.${op.modName}`, impl: op.implName })),
  };
}

/** パス中の {rawName} を Python のパラメータ名に置き換える */
export function pathWithPyNames(op) {
  return op.params.filter((p) => p.in === 'path').reduce((s, p) => s.replace(`{${p.rawName}}`, `{${p.pyName}}`), op.path);
}
